### ISSUE TITLE
Revamp deployment pipeline

### ISSUE THREAD

**Issue by aaron-wu1** [jlab-sensing/DirtViz#101]
I'm thinking about moving completely to trunk-based deployment so that changes can be seen sooner and quicker. 
Rough outline of TODOs:
- [x] Design a CI/CD pipeline
- [x] Rework github actions deployments
- [x] clean up dangling branches on main repo
- [x] fix lint and test stage
- [x] Write a contribution guideline

**Comment by jmadden173** [comment]
@aaron-wu1 would there be separate trunks for the frontend and backend?
