### ISSUE TITLE
update OSRE project description 

### ISSUE THREAD

**Issue by cjosephson** [jlab-sensing/DirtViz#144]
Instruction here: https://ucsc-ospo.github.io/osredocs/formentors/

Old/current description here: https://ucsc-ospo.github.io/project/osre23/ucsc/dirtviz/

**Comment by cjosephson** [comment]
Due date Jan 31, 2024

**Comment by jmadden173** [comment]
Added changes and made PR here: https://github.com/ucsc-ospo/ucsc-ospo.github.io/pull/348

Waiting for @aaron-wu1 to check it over once more
