### ISSUE TITLE
add tooltips

### ISSUE THREAD

**Issue by cjosephson** [jlab-sensing/DirtViz#156]
not sure what some of these buttons do, would be good to add mouseover tooltips

<img width="217" alt="image" src="https://github.com/jlab-sensing/DirtViz/assets/707398/c1e42496-103e-4de2-8fd4-5ee985272db9">

**Comment by Shaburu** [comment]
can i be assigned this issue if no one is working on it?

**Comment by ay-bh** [comment]
@cjosephson I would like to work on this.
