### ISSUE TITLE
page for users to setup their own cells

### ISSUE THREAD

**Issue by aaron-wu1** [jlab-sensing/DirtViz#170]
Currently, in uploading power and teros data, cells are created based on a provided name from `uploader.yaml`. If a cell name is already in the database, then the cell is never created. To circumvent this issue, cells should be manually created by the user before uploading data. The page should walk the user through how to create their cell as well as setup everything up that is needed in the backend for the endpoint `/sensor` to function without returning None for cell.

**Comment by Srishti-j18** [comment]
Hi @aaron-wu1 @jmadden173 !
I'm Srishti Jaiswal. I've successfully set up DirtViz on my local machine. Can I take on this issue? 
if this issue still open to work..
I've also sent you a direct message on Slack and an email to jmadden.
