### ISSUE TITLE
Missing positional Argument 'query', Due to sqlalchemy update

### ISSUE THREAD

**Issue by CSEsteve** [jlab-sensing/DirtViz#66]
When migrating the database conn.py throws a missing argument error. 

Most likely due to sqalchemy update from version 1.0 to 2.0.

![image](https://user-images.githubusercontent.com/66144060/217645197-b6330b57-5944-479e-9e78-5c7e3455b0ee.png)

**Comment by jmadden173** [comment]
@CSEsteve Next time when copying code like text can you put in a code block on github. That way other people are able to copy and paste the text rather than have to type it out when searching for an error.
