### ISSUE TITLE
Graph scaling

### ISSUE THREAD

**Issue by jmadden173** [jlab-sensing/DirtViz#91]
The current plot and subsequently the power plot are off by a factor of 1e-6. My first thought is that a factor of 1e-6 is being applied. Perhaps due to the previous data from the RLs being in nA. Added picture for reference from the `data-collection` branch. Maybe its fixed in `main`?

@cjosephson mentioned this in the most recent EE meeting

![image](https://github.com/jlab-sensing/DirtViz/assets/31051736/da9a0605-912f-4b2f-a976-0f0d6783da05)

**Comment by aaron-wu1** [comment]
I'm looking at the database now and it seems like voltages are around ~0.1-0.5 and current is ~8.0^-5. Also currently power is being calculated by voltage * current, which is why the plot is around 1.0^-6 range. Maybe either voltage or current are in the wrong units?

**Comment by jmadden173** [comment]
Update title for graph scaling as on the voltage/current graphs, the axis are not centered around 0 which makes it confusing when there is 0 voltage and current. Example plot below

![image](https://github.com/jlab-sensing/DirtViz/assets/31051736/c95e0f61-5dcf-48f0-98e2-40365d0e808e)

**Comment by jmadden173** [comment]
> I'm looking at the database now and it seems like voltages are around ~0.1-0.5 and current is ~8.0^-5. Also currently power is being calculated by voltage * current, which is why the plot is around 1.0^-6 range. Maybe either voltage or current are in the wrong units?

I think that it has something to do with the scaling of the data. The voltages are in `V` and the current is in `A`, therefore the current should be multiplied by 1e6 to put it in `mV`. I don't think that is being applied here.

**Comment by aaron-wu1** [comment]
Notes: Make 0s aligned, don't cut out negatives
